apiVersion: v1
kind: Pod
metadata:
  name: http-probe
spec:
  containers:
    - name: http-probe
      image: http-server
      lifecycle:
        postStart:
          exec:
            command: ["/bin/sh", "-c", "echo http server start now > /var/log/message"]
        preStop:
          exec:
            command: [ "/bin/sh","-c","echo http server pod is going to stop> /var/log/message" ]
      readinessProbe:
        httpGet:
          ### this probe will fail with 404 error code
          ### only httpcode between 200-400 is retreated as success
          path: /healthz
          port: 80
        initialDelaySeconds: 10
        periodSeconds: 5
        successThreshold: 2